version: 0.0
os: linux

files:
  - source: / # I need to deploy all files
    destination: /home/ubuntu/price-tracking/Web-Scrapper #store my deploy on this path in the EC2
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300 #max time to executing this script
      runas: root #sspecify the user who going to run this
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
