version: 0.0
os: linux
files:
  - source: / # I need to deploy all files 
    destination: /home/ec2-user/app #store my deploy on this path in the EC2
  hooks:
    BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root   
  
    ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root

    ValidateService:
    - location: scripts/validate_service
      timeout: 300
      runas: root

    ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
