package constants

const MY_EMAIL = "MY_EMAIL"
const ACCOUNT_VERIFICATION_SUBJECT = "Verificacion de correo electronico Tracking de precios"
const LOWER_NOTIFICATION_SUBJECT = "Notificacion de precio bajo"
const SMTP_HOST = "smtp.gmail.com"
const FROM_HEADER = "From"
const TO_HEADER = "To"
const SUBJECT_HEADER = "Subject"
const CONTENT_TYPE_EMAIL = "text/html"
const EMAIL_PASSWORD = "EMAIL_PASSWORD"
const APP_NAME = "Price Tracker"
const VERIFICATION_TEMPLATE_ABSOLUTE_ADDRESS = "./src/services/emails/templates/emailVerification.template.html"
const VERIFICATION_TEMPLATE_RELATIVE_ADDRESS = "./templates/emailVerification.template.html"
const LOWER_PRICE_TEMPLATE_ABSOLUTE_ADDRESS = "./src/services/emails/templates/templates/lowerPriceNotification.template.html"
const LOWER_PRICE_TEMPLATE_RELATIVE_ADDRESS = "./templates/lowerPriceNotification.template.html"
const USER_QUERY = "user"
const TIME_QUERY = "time"
const VERIFICATION_URL = "http://34.201.67.200:3000/verify"
